### ISSUE TITLE
consider alternative: not an atom package but a linux utility

### ISSUE THREAD

**Issue by ljburtz** [ayurmedia/atom-sync-cygwin#16]
This is not an issue, but a pointer for others that might be like me looking for a way to use atom locally with files on a remote server.

This workflow requires two-way realtime sync.

atom-sync does not work well, has a lot of manual clicking required and has been abandoned for 5 years now.
INSTEAD this other project works wonders: https://github.com/stephenh/mirror

I highly recommend it for this particular use case that atom-sync is not made for!

**Comment by ayurmedia** [comment]
I use phpstorm now, and don't support this Plugin anymore. I will merge pull request if you have bugfixes only. Nice to see an alternative solution.

**Comment by ayurmedia** [comment]
Thanks for the tipp.
